/** Config */
export const SET_LAYOUT_TYPE = 'SET_LAYOUT_TYPE'
export const SET_READ_ONLY = 'SET_READ_ONLY'
export const SET_FILENAME = 'SET_FILENAME'
export const SET_LIBRARY = 'SET_LIBRARY'
export const SET_LIBRARY_SUCCESS = 'SET_LIBRARY_SUCCESS'
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB'

/** Editor */
export const SET_EDITOR_VALUE = 'SET_EDITOR_VALUE'
export const EVAL_EDITOR = 'EVAL_EDITOR'
export const SAVE_EDITOR = 'SAVE_EDITOR'
export const SAVE_EDITOR_SUCCESS = 'SAVE_EDITOR_SUCCESS'

/** Interpreter */
export const EVAL_INTERPRETER = 'EVAL_INTERPRETER'
export const EVAL_INTERPRETER_SUCCESS = 'EVAL_INTERPRETER_SUCCESS'
export const EVAL_INTERPRETER_ERROR = 'EVAL_INTERPRETER_ERROR'
export const CREATE_INTERPRETER_OUTPUT = 'CREATE_INTERPRETER_OUTPUT'
export const CLEAR_INTERPRETER = 'CLEAR_INTERPRETER'
export const INTERRUPT_EXECUTION = 'INTERRUPT_EXECUTION'

/** Comments */
export const SET_NEW_COMMENT_VALUE = 'SET_NEW_COMMENT_VALUE'
export const CREATE_COMMENT = 'CREATE_COMMENT'
export const CREATE_COMMENT_SUCESS = 'CREATE_COMMENT_SUCCESS'

/** MCQ Choice  */
export const SELECT_CHOICE = 'SELECT_CHOICE'
export const SELECT_CHOICE_SUCCESS = 'SELECT_CHOICE_SUCCESS'

/** Unit Tests */
export const RUN_TESTS = 'RUN_TESTS'
export const RUN_TESTS_SUCCESS = 'RUN_TESTS_SUCCESS'
